[build]
    base = ""
    publish = "build"
    command = "REACT_APP_STAGE=dev npm run build"
[context.production]
    command = "REACT_APP_STAGE=prod npm run build"
[context.deploy-preview]
    command = "REACT_APP_STAGE=dev npm run build"
[context.branch-deploy]
    command = "REACT_APP_STAGE=dev npm run build"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200